name: SimplySurvival
version: 1.0
main: com.jaeheonshim.simplysurvival.SimplySurvivalPlugin
commands:
  clan:
    description: Run clan based commands
    usage: /<command> <action>
  mute:
    description: Mute a player for a specified duration
    usage: /<command> <username> <hrs|mins> [reason]
    permission: simplysurvival.admin
permissions:
  simplysurvival.admin:
    default:
      op