name: SimplySurvival
version: 1.0
main: com.jaeheonshim.simplysurvival.SimplySurvivalPlugin
commands:
  clan:
    description: Run clan based commands
    usage: /<command> <action>
  mute:
    description: Mute a player for a specified duration
    usage: /<command> <username> <hrs|mins> [reason]
    permission: simplysurvival.admin
  suicide:
    description: Instantly kills you
    usage: /<command>
  enablepvp:
    description: Disable your pvp protection
    usage: /<enablepvp>
  spawn:
    description: Teleports you to spawn
    usage: /<spawn>
  help:
    description: Get help commands
    usage: /<command>
permissions:
  simplysurvival.admin:
    default:
      op